name: rick_and_morty
description: Rick and Morty Characters App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.3
  flutter_hooks: ^0.20.3

  # Network
  dio: ^5.8.0
  connectivity_plus: ^6.1.4

  # Local Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Utils
  fpdart: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.3.7

  # Code generation
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  freezed: ^2.4.1
  json_serializable: ^6.7.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
